### ISSUE TITLE
Question on R1, R2, t1, t2

### ISSUE THREAD

**Issue by HareshKarnan** [mzki/homography-camera-displacement#1]
Thanks for the code. Could you please explain how you got the R1, R2, t1, t2 matrices ? Why is it that they are in the camera frame ? I find it hard to visualize it in camera frame

**Comment by mzki** [comment]
Hi @HareshKarnan 

Sorry for the late reply. I will try to explain as I can remember.

> Could you please explain how you got the R1, R2, t1, t2 matrices ?

These are the settings for the camera posture on the 3D modeling tool.
First, I defined an object coordinate system such that the mesh grid has Y=0 and lies on the XZ plane (the direction of the XYZ axes follows the OpenCV coordinate system). R1 and R2 are set in the modeling tool as 60 degrees downward and 90 degrees downward from the object coordinate system, respectively. Similarly, the camera positions t1 and t2 are set in the modeling tool in the object coordinate system. (e.g. [0, -0.866, 0] is the position of camera 1 in the object coordinate system.) Then, the rotation matrices R1 and R2 are applied to t1 and t2 in the object coordinate system to represent them in the camera coordinate system. 

> Why is it that they are in the camera frame ? I find it hard to visualize it in camera frame

Because the homography equation uses R1, R2, t1 and t2 as such coordinate system.
You can visualize these in object coordinate system since the values are described at the notebook.

**Comment by HareshKarnan** [comment]
Thanks for the reply. If the object coordinate frame is as you say, with Y axes pointed up, shouldn't t1 be [0, 0.866, 0] ? Why the negative ? since the camera is above the ground.

**Comment by mzki** [comment]
Because XYZ axes of the object coordinate frame follows the OpenCV one, meaning Y axes pointed down for positive.

**Comment by HareshKarnan** [comment]
oh i see. thanks !
